image: python:latest

stages:
  - build
  - test
  - deploy

variables:
  API_KEY: $API_KEY

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - python -m compileall .
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - echo "from setuptools import setup, find_packages; setup(name='localtime-cli', version='1.0', packages=find_packages(), install_requires=['requests', 'dotenvfile'])" > setup.py
    - python setup.py install
    - python -m unittest discover -s tests -p 'test_*.py'
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - main
