image: python:latest

stages:
  - build
  - test
  - deploy

variables:
  API_KEY: $API_KEY

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - python -m compileall .
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - pip install pytest
    - pytest tests/
    - python test-localtime-cli.py --help
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - main
